#!/usr/bin/env bash

# Note 1: This server will kill all ffmpeg processes, so doesn't coexist with other applications well!
# Note 2: This script requires passwordless sudo

source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)";
cd "${source_dir}";

COLOUR_GREEN='\033[0;32m'
COLOUR_YELLOW='\033[0;33m'
COLOUR_PURPLE='\033[0;35m'
COLOUR_RED='\033[0;31m'
DECOR_BOLD='\033[1m';
COLOUR_DECOR_OFF='\033[0;00m'
CLEAR_LINE='\033[2K'

if [ ! -f "camera-credentials" ];
then
    echo -e "${COLOUR_RED}${DECOR_BOLD}Error${COLOUR_DECOR_OFF}: Configuration file '${DECOR_BOLD}camera-credentials${COLOUR_DECOR_OFF}' not found.";
    echo " - Copy 'camera-credentials.template' to 'camera-credentials'";
    echo " - Edit 'camera-credentials' for your camera & stream login details.";
    exit 1;
fi

source camera-credentials;

fail=10
while [ 1 ];
do
  echo "SWHR rtmp-watchdog: querying server..";
  if curl -s 'https://swhr.org.uk/rtmp/status' | grep "<name>${RTMP_STREAM_NAME}</name>" >/dev/null;
  then
    # We got a response and the RTMP_STREAM_NAME was in it, so all ok, reset counter
    echo "SWHR rtmp-watchdog: stream ok";
    fail=10
  else
    # Either there was no response, so internet is down and maybe a good idea to restart ffmpeg anyway,
    #  or we got a response, but the stream isn't running, so we might need to restart ffmpeg
    #  so, decrement the counter
    fail=$((fail-1))
    echo "SWHR rtmp-watchdog: WARNING stream fail! ${fail} attempts remaining";
    # The counter will be less than 1 if we've had 10 consecutive failures (approx 12 seconds or a bit more)
    if [[ "${fail}" -lt 1 ]];
    then
      # Counter is 0, so reset ffmpeg, then give it a bit longer (~25 seconds) for the stream to come back
      echo "SWHR rtmp-watchdog: Killing ffmpeg so it restarts!";
      sudo killall -9 ffmpeg;
      fail=20
    fi
  fi
  sleep 1;
done
